### ISSUE TITLE
Getting invalid torrentid on production server

### ISSUE THREAD

**Issue by owen800q** [Davenchy/live-torrent#51]
Either pass torrent's infohash or the full URL to that torrent file, none of them works on production server http://live-torrent.herokuapp.com. The example url is https://dl.dmhy.org/2020/03/25/57d9d96bcd814e1de92e64f530056ec73479eaf8.torrent

![live-torrent-demo](https://user-images.githubusercontent.com/19252045/77604939-a2578b80-6f4e-11ea-8be4-cace008dab41.gif)

But working on development server.

![image](https://user-images.githubusercontent.com/19252045/77604999-c4510e00-6f4e-11ea-9721-0af58460adcb.png)

**Comment by owen800q** [comment]
@Davenchy

**Comment by Davenchy** [comment]
Sorry Bro, I am using Heroku the free plan and I used all my online hours for this month, I was thinking in some hacks to solve this issue, but for the current version of live-torrent I can't do it.
Sorry again, for now you can use it on localhost by cloning and installing the project or by using docker.
You will find more information in the README.md file for both ways.
And I am working on separated frontend and backend which will help to add my idea as a solution or hosting live-torrent on netlify or now and live-torrent-backend on heroku.
Feel free to reopening if you think it is not related to heroku.
Happy Day.
