### ISSUE TITLE
Failed to load captions

### ISSUE THREAD

**Issue by AyaanZaveri** [Davenchy/live-torrent#67]
![Screenshot 2020-06-20 at 5 51 21 PM](https://user-images.githubusercontent.com/63752541/85212244-e45e5680-b31e-11ea-9460-4b3db6661b19.png)

**Comment by Davenchy** [comment]
can I ask how to reproduce this error, Is this just happens when you watch a movie from the yts page, or after selecting a video file from a torrent file, are you running Live Torrent locally or hosted.
Please I need more details.
Thank you for your feedback, Stay home and be safe.

**Comment by GeekNAUer** [comment]
oh, i have the same problem. If you deploy it to heroku, you will have this problem no matter what film you are watching.

**Comment by Davenchy** [comment]
I have the same problem and when I checked it, I found that the opensubtitles server returns this message `506 Server under maintenance`, So for now I will wait till opensubtitles server returns back then I will check it again.
